# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 999a24b68ec7ec8292c8260672e4650d24f3c72276859b2b095662f75f2a5cb3d65f4959f990b5f3aca772a90d9007923cca5e127875adb700fb60ec70983e01

test:
  secret_key_base: 6c8b78113368bcb85b1eee2f0587b32b2f925d5c1379d822e8fbc86bae89c990966baa852a45580aaf186b61aacb58fff7be29713082dbd050db7f78a7bec2b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
